### ISSUE TITLE
Adding 1 vs 1 game modes

### ISSUE THREAD

**Issue by amrit-choudhary** [vineetjc/pygame-Coin-Fall-#25]
Add different game modes to the game. When you click on play it will give you a menu with game modes to choose from.

First idea: 1 v 1. One player plays by keys A and D and other by arrow keys. Who has more keys at end wins. There is no cart collision.

Please submit you own game mode ideas too.

**Comment by vineetjc** [comment]
Leaving it open for other peers to contribute to

**Comment by vineetjc** [comment]
1v1 as in split screen?

**Comment by amrit-choudhary** [comment]
One screen is enough. We just need 2 carts.

**Comment by kartikct25** [comment]
One more idea...We can also ask player for difficulty level,,,it will change speed of coin falling according to level.

**Comment by kartikct25** [comment]
> One more idea...We can also ask player for difficulty level,,,it will change speed of coin falling according to level.

Can I work on this??

**Comment by amrit-choudhary** [comment]
This is a great idea. I will make a new issue then we can discuss there.

**Comment by amrit-choudhary** [comment]
added #57
