### ISSUE TITLE
Button functions on mouse scroll up and down

### ISSUE THREAD

**Issue by vineetjc** [vineetjc/pygame-Coin-Fall-#36]
Scroll up or down on a button and it is the same as a mouse click, incorrect mouse functions called on buttons, needs to be fixed. Not seemingly urgent, but unnecessary indeed.

**Comment by amrit-choudhary** [comment]
fixed #37

**Comment by amrit-choudhary** [comment]
issue can be closed

**Comment by vineetjc** [comment]
Following buttons have this bug:

- All in the start screen (Start Game, tutorial, settings, credits, exit)
- Inside 'Start Game' (Easy, Medium, Hard, Back buttons)
- End of a game (Restart, Back buttons)

**Comment by amrit-choudhary** [comment]
fixed in #50

**Comment by vineetjc** [comment]
I'm going to close this wrt #50.
