### ISSUE TITLE
Difficulty Settings: Defining difficulty parameters

### ISSUE THREAD

**Issue by amrit-choudhary** [vineetjc/pygame-Coin-Fall-#38]
Add difficulty settings to the game.
Will affect coin fall speed

**Comment by amrit-choudhary** [comment]
Suggestions for implementation:
1. Add a new screen, which comes after clicking on Start Game
2. It will have buttons for game mode selection, difficulty selection etc. Right now only add buttons for difficulty selection.
3. Selecting difficulty will save it as a variable in game_manager
4. Play the selected game mode (right now we only have one)
5. When the game starts, it will use the variable saved in game_manager

**Comment by amrit-choudhary** [comment]
To implement a new screen, please look at how credits_screen is done.
It was done is <15 minutes. Follow the same structure / method.

**Comment by kartikct25** [comment]
I'll work on this

**Comment by amrit-choudhary** [comment]
awesome!
let me know if you have any problems

**Comment by kartikct25** [comment]
@amrit-choudhary   have added a screen and variables in game_manager ..but i am facing problem in using these variables in game_screen ...Can you tell me how should I use them to control number of coin falling?

**Comment by amrit-choudhary** [comment]
problem in getting variable from game_manager or problem in using it?

**Comment by kartikct25** [comment]
What I did was ...I returned integer value from my gameMode_screen to a parameter in game_screen and use this parameter as slicing number
in
<for b in self.coinlist[0:self.i:15]: >

used that number in place of 15...but it caused an error

**Comment by amrit-choudhary** [comment]
The speed at which coins fall is actually controlled by this function

def fall():
    self.y += 7

here 7 is the actual speed of all

this should be changed based on difficulty

in the coin's __init__ function, take a new parameter speed, which depends on difficulty
then use that speed var instead of 7

**Comment by amrit-choudhary** [comment]
def fall(): can be found in src/objects/coin.py

**Comment by kartikct25** [comment]
Speed changing is also good...
but I thought to set density of coin fall would be better for difficulty leveling
What you say?

**Comment by kartikct25** [comment]
We can change speed for infinite mode

**Comment by amrit-choudhary** [comment]
then change this
def get_random_entity
in game_screen.py

**Comment by amrit-choudhary** [comment]
get_random_entity function is very bad right now, please change it to something good
it's called every frame
make it more predictable
for example:
75% of the time, nothing will drop
20% of the time, silver coin drops
10% of the time, gold coin drops
5% of the time, bomb drops

and have these values 75, 20, 10 and 5 as variables that are set through difficulty

for example in hard it's 55, 20, 10, 25

**Comment by amrit-choudhary** [comment]
if you have trouble implementing above, 
here's a hint, 
get a random int from 0 - 100
if num is < 75
....do nothing
elif num < 90
....do silver coin

**Comment by kartikct25** [comment]
@amrit-choudhary @vineetjc  I have created a pull request for this issue ...though I have not changed 
<get_random_entity> function   ..but it is working great

**Comment by amrit-choudhary** [comment]
added in #57, can be closed
