### ISSUE TITLE
Feature: Game Mode: Infinite Mode

### ISSUE THREAD

**Issue by amrit-choudhary** [vineetjc/pygame-Coin-Fall-#39]
No time limit.
The coin fall speed increases slowly over time (similar to temple run or other infinite runners)
Game end condition: hitting bomb

Optional:
Game end condition: missing a lot of coins in a row.

**Comment by kartikct25** [comment]
@amrit-choudhary  are you doing it ?

**Comment by amrit-choudhary** [comment]
You can do this one. I can work on 1 v 1 game mode.

**Comment by kartikct25** [comment]
Ok .

So what I have add it..?

>other screen before game mode screen having options of two mode 

>One mode for simple difficulty and then goes same
> Another After pressing infinite mode it will go to game screen ,having no time limit ,score multiplier increases with time 


Anything else

**Comment by kartikct25** [comment]
And also game end condition 

+??

**Comment by amrit-choudhary** [comment]
You have already made a game mode screen.
just add 2 button, classic and infinite

game end condition is getting hit by bomb

**Comment by amrit-choudhary** [comment]
also, this high score should be saved separately.
so in the game_manager, make a new highscore_infinite.
and when you die in infinite mode when you die
you go to different game_over_screen
which shows your highscore_infinite

**Comment by amrit-choudhary** [comment]
actually, highscore saving needs to be changed.

so for now just make a new game_over_infinite_screen
same as game_over_screen
only thing that changes is Restart button will take to game_infinite_screen

**Comment by kartikct25** [comment]
What is classic mode

**Comment by amrit-choudhary** [comment]
classic = the game that we have right now.

**Comment by kartikct25** [comment]
That means classic will return difficulty level screen??

**Comment by amrit-choudhary** [comment]
infinite game is a new game screen.
clicking on classic will take you to the current game screen
clicking on infinite will take you to the infinite game screen

**Comment by amrit-choudhary** [comment]
just like how you created a game_mode_screen
create a new game_infinite_screen and add a new item to Game_mode enum.
most of the code of game_infinite_screen is same as game_screen.
just make it infinite.

in your game_mode screen
when you click on classic it will load game_screen
when you click on infinite it will load game_infinite_screen

**Comment by amrit-choudhary** [comment]
also, you should wait for #45 to get merged, then take a pull. It has lots of changes.

**Comment by amrit-choudhary** [comment]
added #57
