### ISSUE TITLE
For Everyone: Indentation Issues

### ISSUE THREAD

**Issue by amrit-choudhary** [vineetjc/pygame-Coin-Fall-#44]
Python 3 doesn't allow mixing tabs with space.
So everyone configure your editor to have the following settings:
1. tab = 4 spaces
2. tabs are automatically converted to spaces

Commits without this shouldn't be accepted, because everyone has to spend hours fixing someone else's errors.

**Comment by imskr** [comment]
I'm fixing this issue as main.py isn't at pep8 standard

**Comment by amrit-choudhary** [comment]
this is for all future commits.
I've already fixed main.py for pep8

**Comment by imskr** [comment]
It is still showing errors!  I think it has some errors

**Comment by amrit-choudhary** [comment]
let #45 get merged. Then you can take a pull and check for errors.

**Comment by amrit-choudhary** [comment]
how are you checking for pep8?

**Comment by imskr** [comment]
using pycodestyle

**Comment by amrit-choudhary** [comment]
Hi, i have edited main.py in #45 
can you please check if it's pep8
```python
import sys
import pygame
from pygame.locals import QUIT, KEYUP
from src.misc.game_enums import Game_mode, Entity
from src.managers import *
from src.game_screens import *
from src.input_package import input_manager


def game_loop():
    pygame.init()

    # setup the window display
    size = (1024, 768)
    windowSurface = pygame.display.set_mode(size, 0, 32)
    pygame.display.set_caption('Coin Fall')

    # initialize resources and game mode
    res = Resources(pygame)
    game_clock = pygame.time.Clock()
    game_mode = Game_mode.MAIN_MENU
    game_manager = Game_manager()
    game_manager.set_input(input_manager.Input_Manager())

    # set game logo
    pygame.display.set_icon(res.logo)

    # initialize screens
    main_menu_screen = Main_menu_screen(pygame, res, windowSurface)
    game_screen = Game_screen(
        pygame, res, windowSurface, size, game_clock, game_manager)
    settings_screen = Settings_screen(pygame, res, windowSurface)
    game_over_screen = Game_over_screen(
        pygame, res, windowSurface, game_manager)
    tutorial_screen = Tutorial_screen(pygame, res, windowSurface)
    credits_screen = Credits_screen(pygame, res, windowSurface)
    game_mode_screen = Game_Mode_Screen(
        pygame, res, windowSurface, game_manager)

    # game loop starts
    while True:
        events = pygame.event.get()
        game_manager.input.update(events)

        if game_mode == Game_mode.MAIN_MENU:
            game_mode = main_menu_screen.update(events)

        elif game_mode == Game_mode.GAME:
            game_mode = game_screen.update(events)

        elif game_mode == Game_mode.SETTINGS:
            game_mode = settings_screen.update(events)

        elif game_mode == Game_mode.GAME_OVER:
            game_mode = game_over_screen.update(events)

        elif game_mode == Game_mode.TUTORIAL:
            game_mode = tutorial_screen.update(events)

        elif game_mode == Game_mode.CREDITS:
            game_mode = credits_screen.update(events)

        elif game_mode == Game_mode.GAME_MODE:
            game_mode = game_mode_screen.update(events)

        else:
            pygame.quit()
            sys.exit()

        game_clock.tick(60)


if __name__ == "__main__":
    game_loop()
```

**Comment by imskr** [comment]
yes it is alright So should i close my PR

**Comment by amrit-choudhary** [comment]
yeah, go ahead.
I have made the whole project pep8 compliant, except for E501: line too long at some places
E501 is ignored by a lot of developers.

If you want to check, make a clone of this
https://github.com/amrit-choudhary/pygame-Coin-Fall-.git
and check the feature branch.

**Comment by imskr** [comment]
E501: line too long at some places It can also be solved. check code #46

**Comment by amrit-choudhary** [comment]
I know, but sometimes, it can cause errors or make the code more unreadable. That's why some devs ignore it.

**Comment by imskr** [comment]
yeah ok! why there are so many PRs open.

**Comment by amrit-choudhary** [comment]
only one guy has merge rights and he is busy

**Comment by vineetjc** [comment]
@imskr @amrit-choudhary I try my best to check PRs everyday, some are still under 'Changes requested', others I will review now. If something needs to be urgently checked, just message me stating the same.

**Comment by vineetjc** [comment]
@amrit-choudhary can I close this? As this could rather just be a general note to all contributors.

**Comment by amrit-choudhary** [comment]
Yeah close it. Just make sure new contributors know about this issue somehow.
