### ISSUE TITLE
Improve end screen and restart

### ISSUE THREAD

**Issue by vineetjc** [vineetjc/pygame-Coin-Fall-#5]

**Comment by vineetjc** [comment]
PR #9 adds restart feature, to improve this by making an end screen and incorporating restart into that.

**Comment by vineetjc** [comment]
PR #12 adds game screens, can still use improvements on visuals, also needs fix for #14

**Comment by divyang-mittal** [comment]
PR #23 adds a background image for end screen

**Comment by vineetjc** [comment]
Closing this as we now have an end screen and restart button.
