### ISSUE TITLE
Extra Feature: Train an AI to play the game.

### ISSUE THREAD

**Issue by amrit-choudhary** [vineetjc/pygame-Coin-Fall-#51]
If someone is interested in machine learning and AI, you can try creating an AI that will play this game.

**Comment by deepak2431** [comment]
Currently  I am learning machine learning and want to work on this . How can I do that ?

**Comment by amrit-choudhary** [comment]
@deepak2431 You want help on which part? AI or this game?
I can create a level where you can train the AI. 
Basically, I will give you a list of coins and their positions on screen. The cart's position as well. 
The AI has to give an input. Either right, left or nothing.

**Comment by deepak2431** [comment]
I want to help on the AI part.Train the model to play the game.

**Comment by vineetjc** [comment]
This is very open ended, I'll leave this as a hard, long-term work and I'm very interested to contribute as well

**Comment by amrit-choudhary** [comment]
I will make a demo AI game mode, where a very stupid AI will play the game. You guys can replace that AI script with your own better AI scripts and test.

**Comment by vineetjc** [comment]
Implemented in #60, improving it is a very general thing.
